{
  "runnable": false,
  "phase": "repair",
  "error_type": "RuntimeError",
  "message": "Traceback (most recent call last):\n  File \"/home/wan00559/pipleline/utils/compile_and_run.py\", line 525, in compare_and_bench\n    test_out, _ = _run_once(test_model, inp, dev)\n                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/wan00559/pipleline/utils/compile_and_run.py\", line 127, in _run_once\n    out = model(*inp)\n          ^^^^^^^^^^^\n  File \"/home/wan00559/miniconda3/envs/maxk/lib/python3.11/site-packages/torch/nn/modules/module.py\", line 1751, in _wrapped_call_impl\n    return self._call_impl(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/wan00559/miniconda3/envs/maxk/lib/python3.11/site-packages/torch/nn/modules/module.py\", line 1762, in _call_impl\n    return forward_call(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/wan00559/pipleline/run/20250828_191048_48_Mamba2ReturnY/48_Mamba2ReturnY/code/kernel_20250828_191611.py\", line 156, in forward\n    X_blocks, A_blocks, B_blocks, C_blocks = [\n                                             ^\n  File \"/home/wan00559/pipleline/run/20250828_191048_48_Mamba2ReturnY/48_Mamba2ReturnY/code/kernel_20250828_191611.py\", line 157, in <listcomp>\n    torch.einsum(\"b (c l) ... -> b c l ...\", t, self.block_len)\n  File \"/home/wan00559/miniconda3/envs/maxk/lib/python3.11/site-packages/torch/functional.py\", line 422, in einsum\n    return _VF.einsum(equation, operands)  # type: ignore[attr-defined]\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nTypeError: expected Tensor as element 1 in argument 1, but got int\n"
}