{
  "runnable": false,
  "phase": "repair",
  "error_type": "RuntimeError",
  "message": "Traceback (most recent call last):\n  File \"/home/wan00559/pipleline/utils/compile_and_run.py\", line 519, in compare_and_bench\n    align_stats = try_align_params(ref_model, test_model, ref_mod=ref_mod, test_mod=test_mod)\n                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/wan00559/miniconda3/envs/maxk/lib/python3.11/site-packages/torch/utils/_contextlib.py\", line 116, in decorate_context\n    return func(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/wan00559/pipleline/utils/compile_and_run.py\", line 410, in try_align_params\n    stats = _PAIR_ALIGNERS[key_class](ref_model, test_model)\n            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/wan00559/miniconda3/envs/maxk/lib/python3.11/site-packages/torch/utils/_contextlib.py\", line 116, in decorate_context\n    return func(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/wan00559/pipleline/utils/compile_and_run.py\", line 385, in _align_Model_to_ModelNew\n    stats = align_params_generic(ref_model, test_model)\n            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/wan00559/miniconda3/envs/maxk/lib/python3.11/site-packages/torch/utils/_contextlib.py\", line 116, in decorate_context\n    return func(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/wan00559/pipleline/utils/compile_and_run.py\", line 274, in align_params_generic\n    if t_src is not None and _safe_copy_(t_dst, t_src):\n                             ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/wan00559/miniconda3/envs/maxk/lib/python3.11/site-packages/torch/utils/_contextlib.py\", line 116, in decorate_context\n    return func(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/wan00559/pipleline/utils/compile_and_run.py\", line 206, in _safe_copy_\n    if dst.shape != src.shape:\n       ^^^^^^^^^\n  File \"/home/wan00559/miniconda3/envs/maxk/lib/python3.11/site-packages/torch/nn/parameter.py\", line 139, in shape\n    raise RuntimeError(\nRuntimeError: Can't access the shape of an uninitialized parameter or buffer. This error usually happens in `load_state_dict` when trying to load an uninitialized parameter into an initialized one. Call `forward` to initialize the parameters before accessing their attributes.\n"
}