{
  "runnable": false,
  "phase": "repair",
  "error_type": "RuntimeError",
  "message": "Traceback (most recent call last):\n  File \"/home/wan00559/pipleline/utils/compile_and_run.py\", line 516, in compare_and_bench\n    test_model = ModelNew(*init_args, **init_kwargs)\n                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/wan00559/pipleline/run/20250828_154447_batch_first13/5_AlexNet/code/kernel_20250828_170153.py\", line 168, in __init__\n    self.fc1 = FusedLinearReLU(256 * 2 * 2, 4096)   # 256 channels \u00d7 2 \u00d7 2 spatial\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/wan00559/pipleline/run/20250828_154447_batch_first13/5_AlexNet/code/kernel_20250828_170153.py\", line 130, in __init__\n    self.reset_parameters()\n  File \"/home/wan00559/pipleline/run/20250828_154447_batch_first13/5_AlexNet/code/kernel_20250828_170153.py\", line 133, in reset_parameters\n    nn.init.kaiming_uniform_(self.weight, a=torch.sqrt(torch.tensor(5.0)))\n  File \"/home/wan00559/miniconda3/envs/maxk/lib/python3.11/site-packages/torch/nn/init.py\", line 514, in kaiming_uniform_\n    gain = calculate_gain(nonlinearity, a)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/wan00559/miniconda3/envs/maxk/lib/python3.11/site-packages/torch/nn/init.py\", line 132, in calculate_gain\n    raise ValueError(f\"negative_slope {param} not a valid number\")\nValueError: negative_slope 2.2360680103302 not a valid number\n"
}